spring:
  application:
    name: restful-practice
  jackson:
    default-property-inclusion: non_null
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: af6cad3b-521e-4cb6-8e8e-9abb10b132ad

server:
  port: 8787

dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: "*"
