spring:
  application:
    name: hello-multi-ds
  #  main:
  #    allow-bean-definition-overriding: true
  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: 127.0.0.1:8848
  #        namespace: 0b5efed2-4715-47e0-a060-c6f426a1fc46
  #        group: example4
  #      config:
  #        server-addr: 127.0.0.1:8848
  #        namespace: 0b5efed2-4715-47e0-a060-c6f426a1fc46
  #        group: example4
  #  redis:
  #    host: 127.0.0.1
  #    port: 6379
  datasource:
    dynamic:
      primary: master
      lazy: false
      strict: false
      datasource:
        master:
          url: jdbc:mysql://192.168.44.129:3306/spring_cloud_alibaba_practice_master?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
          username: young
          password: "0320"
          maximumPoolSize: 10
          minimumIdle: 2
          idleTimeout: 600000
          connectionTimeout: 30000
          maxLifetime: 1800000
        slave_1:
          url: jdbc:mysql://192.168.44.129:3306/spring_cloud_alibaba_practice_slave1?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
          username: young
          password: "0320"
          maximumPoolSize: 10
          minimumIdle: 2
          idleTimeout: 600000
          connectionTimeout: 30000
          maxLifetime: 1800000
        slave_2:
          url: jdbc:mysql://192.168.44.129:3306/spring_cloud_alibaba_practice_slave2?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
          username: young
          password: "0320"
          maximumPoolSize: 10
          minimumIdle: 2
          idleTimeout: 600000
          connectionTimeout: 30000
          maxLifetime: 1800000
server:
  port: 8067
mybatis-plus:
  type-aliases-package: com.alibaba.cloud.youxia.mapper
  mapper-locations:
    - classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



